# Generated by Django 5.0.6 on 2024-05-15 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Anime', 'Anime'), ('Livro', 'Livro'), ('Filme', 'Filme'), ('Série', 'Série'), ('Dorama', 'Dorama'), ('Documentário', 'Documentário')])),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
