# Generated by Django 5.0.6 on 2024-05-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('serie', 'Série'), ('filme', 'Filme'), ('dorama', 'Dorama')], max_length=10)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(choices=[('hentai', 'Hentai'), ('shojo', 'Shojo'), ('kodomomuke', 'Kodomomuke'), ('shonen', 'Shonen'), ('seinen', 'Seinen'), ('josei', 'Josei'), ('shounen AI', 'Shounen AI'), ('shoujo AI', 'Shoujo AI'), ('yaoi', 'Yaoi'), ('yuri', 'Yuri'), ('mecha', 'Mecha'), ('code gears', 'Code Gears'), ('harem', 'Harem'), ('ecchi', 'Ecchi'), ('harem', 'Harem'), ('Reverse Harem', 'Reverse Harem'), ('yokai', 'Yokai'), ('isekai', 'Isekai'), ('slice of life', 'Slice of Life'), ('iyashikei', 'Iyashikei'), ('idol', 'Idol')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('serie', 'Série'), ('filme', 'Filme'), ('dorama', 'Dorama')], max_length=10)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(choices=[('escolar', 'Escolar'), ('romance', 'Romance'), ('comédia', 'Comédia'), ('histórico', 'Histórico'), ('policial', 'Policial'), ('fantasia', 'Fantasia'), ('terror', 'Terror'), ('médico', 'Médico')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('serie', 'Série'), ('filme', 'Filme'), ('dorama', 'Dorama')], max_length=10)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('serie', 'Série'), ('filme', 'Filme'), ('dorama', 'Dorama')], max_length=10)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('serie', 'Série'), ('filme', 'Filme'), ('dorama', 'Dorama')], max_length=10)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
